### ISSUE TITLE
Deadlock when trying to write IP address to log

### ISSUE THREAD

**Issue by mayhem** [metabrainz/metabrainz.org#155]
On the flipside, logging is working. :)

As for fixing this error, if it occurs again, the error should be logged, but not be fatal. Let the request proceed successfully.

```
   Message type: ERROR
   Location: /home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/flask/app.py:1423
   Module: app
   Function: log_exception
   Time: 2015-05-18 04:10:04,323
   Message:
   Exception on /api/musicbrainz/replication-86400.tar.bz2 [GET]

Traceback (most recent call last):
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "./metabrainz/api/decorators.py", line 16, in decorated
   return f(*args, **kwargs)
 File "./metabrainz/api/decorators.py", line 30, in decorated
   AccessLog.create_record(request.args.get('token'), ip_addr)
 File "./metabrainz/model/access_log.py", line 49, in create_record
   cls.remove_old_ip_addr_records()
 File "./metabrainz/model/access_log.py", line 80, in remove_old_ip_addr_records
   update({cls.ip_address: None})
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2949, in update
   update_op.exec_()
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1074, in exec_
   self._do_exec()
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1223, in _do_exec
   mapper=self.mapper)
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1023, in execute
   bind, close_with_result=True).execute(clause, params or {})
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
   return meth(self, multiparams, params)
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
   return connection._execute_clauseelement(self, multiparams, params)
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
   compiled_sql, distilled_params
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
   context)
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1339, in _handle_dbapi_exception
   exc_info
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
   reraise(type(exception), exception, tb=exc_tb)
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
   context)
 File "/home/metabrainz/metabrainz.org/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
   cursor.execute(statement, parameters)
OperationalError: (psycopg2.extensions.TransactionRollbackError) deadlock detected
DETAIL:  Process 9478 waits for ShareLock on transaction 713369; blocked by process 9522.
Process 9522 waits for ShareLock on transaction 713371; blocked by process 9478.
HINT:  See server log for query details.
[SQL: 'UPDATE access_log SET ip_address=%(ip_address)s WHERE access_log.timestamp < %(timestamp_1)s'] [parameters: {'ip_address': None, 'timestamp_1': datetime.datetime(2015, 5, 18, 3, 10, 3, 240729, tzinfo=<UTC>)}]
```

**Comment by gentlecat** [comment]
Yeah, maybe we should consider adding ways to continue serving replication packets even when DB logging stops working.

**Comment by mayhem** [comment]
Yes, please -- that is what I meant by logging the error, but not propagating it to the user. Return 200 to the user...

**Comment by gentlecat** [comment]
@mayhem, should we close this?

**Comment by mayhem** [comment]
Did you create the cron job?

**Comment by gentlecat** [comment]
No, I thought you'd do that.

**Comment by mayhem** [comment]
I think we should close this and keep logs for now. I'll add a ticket to make a public statement about logging downloads.
